Repository Humans-of-Julia/TypeDBClient.jl, pull requests merged in 2020-11, with the labels that each got.

#2 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#3 Fresh start (with PkgTemplates.jl) + integration of previous code/info
  .github/workflows/ci.yml
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/index.md
  src/GraknClient.jl
Labels: documentation, enhancement

#12 Smoothed the logo and cleaned .toml files
  .gitignore
  Manifest.toml
  Project.toml
  README.md
  docs/Manifest.toml
  docs/Project.toml
  docs/src/assets/custom.css
  docs/src/assets/logo.png
Labels: documentation

#14 Initial Python ci & templates for issues & PR
  .github/templates/ISSUE_TEMPLATE.md
  .github/templates/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
Labels: enhancement
