Repository Humans-of-Julia/TypeDBClient.jl, pull requests merged in 2021-09, with the labels that each got.

#115 make the BDD test run stable and give an result
  test/behaviour/connection/ConnectionStepsBase.jl
  test/runner.jl
Labels: bug

#116 Yaml workflow file to run the BDD test within CI
  .github/workflows/BDD-runner.yml
Labels: Implementation

#117 New status badge for BDD
  README.md
Labels: documentation

#118 Add more time until the request will timed out in schema session in BDD tests
  test/behaviour/features/steps/steps.jl
Labels: bug

#119 changed the requirements in the docs
  docs/Project.toml
Labels: bug
